{% set name = "open62541" %}
{% set version = "1.2.2" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  - url: https://github.com/open62541/open62541/archive/v{{ version }}.tar.gz
    sha256: 9b5bfd811ee523be601f11abc514a93c67fe5c6e957cd6c36fe6ea4f28e009bb

build:
  number: 1
  run_exports:
    - {{ pin_subpackage(name, max_pin='x.x.x') }}

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - make                               # [not win]
    - cmake
    - python
  host:
    - openssl
  run:
    - openssl

test:
  commands:
    - test -f ${PREFIX}/include/open62541/server.h  # [not win]
    - test -f ${PREFIX}/lib/libopen62541.so  # [linux]
    - test -f ${PREFIX}/lib/libopen62541.dylib  # [osx]
    - test -f ${PREFIX}/lib/cmake/open62541/open62541Config.cmake  # [not win]
    - if not exist %PREFIX%\\Library\\include\\open62541\\server.h (exit 1)  # [win]
    - if not exist $PREFIX$\\Library\\lib\\open62541.lib (exit 1)  # [win]
    - if not exist $PREFIX$\\Library\\bin\\open62541.dll (exit 1)  # [win]
    - if not exist %PREFIX%\\Library\\lib\\cmake\\open62541\\open62541Config.cmake (exit 1)  # [win]

about:
  home: https://github.com/open62541/open62541
  license: MPL-2.0
  license_file: LICENSE
  summary: Open source implementation of OPC UA (OPC Unified Architecture) also known as IEC 62541.

extra:
  recipe-maintainers:
    - traversaro
